test_that("printing with and without resolved packages", {
    gran_mixture <- readRDS("../testdata/gran_mixture.RDS")
    gran_ok <- readRDS("../testdata/gran_ok.RDS")
    gran_unresolved <- readRDS("../testdata/gran_unresolved.RDS")
    gran_output <- capture_output(print(gran_ok$grans[[1]]))
    expect_equal(gran_output, "The latest version of `LDAvis` at 2023-01-01 was 0.3.2, which has 2 unique dependencies (2 with no dependencies.)")
    gran_ok_output <- capture_output(print(gran_ok))
    expect_true(grepl("^resolved: 1 package\\(s\\). Unresolved package\\(s\\): 0", gran_ok_output))
    gran_mixture_output <- capture_output(print(gran_mixture))
    expect_true(grepl("^resolved: 1 package\\(s\\). Unresolved package\\(s\\): 1", gran_mixture_output))
    gran_unresolved_output <- capture_output(print(gran_unresolved))
    expect_true(grepl("^resolved: 0 package\\(s\\). Unresolved package\\(s\\): 1", gran_unresolved_output))
    expect_false(grepl("The latest version", gran_unresolved_output))
})

test_that("all_pkgs", {
    gran_mixture <- readRDS("../testdata/gran_mixture.RDS")
    output1 <- capture_output(print(gran_mixture, all_pkgs = FALSE))
    output2 <- capture_output(print(gran_mixture, all_pkgs = TRUE))
    expect_true(output1 == output2)
    gran_6 <- readRDS("../testdata/gran_6.RDS")
    output1 <- capture_output(print(gran_6, all_pkgs = FALSE))
    output2 <- capture_output(print(gran_6, all_pkgs = TRUE))
    expect_false(output1 == output2)
    expect_true(grepl("First 5 packages", output1))
    expect_false(grepl("First 5 packages", output2))
})
