## generated by gran, do not edit by hand

.install_packages <- function(tarball_path, lib, verbose, current_r_version) {
    if (utils::compareVersion(current_r_version, "3.0") != -1) {
        if (is.na(lib)) {
            install.packages(pkg = tarball_path, repos = NULL, verbose = verbose, quiet = !verbose)
        } else {
            install.packages(pkg = tarball_path, lib = lib, repos = NULL, verbose = verbose, quiet = !verbose)
        }
    } else {
        if (is.na(lib)) {
            install.packages(pkg = tarball_path, repos = NULL)
        } else {
            install.packages(pkg = tarball_path, lib = lib, repos = NULL)
        }
    }
}

.download_package <- function(tarball_path, x, verbose) {
    url <- paste(cran_mirror, "src/contrib/Archive/", names(x), "/", names(x), "_", x, ".tar.gz", sep = "")
    tryCatch({
        suppressWarnings(download.file(url, destfile = tarball_path, quiet = !verbose))
    }, error = function(e) {
        ## is the current latest
        url <- paste(cran_mirror, "src/contrib/", names(x), "_", x, ".tar.gz", sep = "")
        download.file(url, destfile = tarball_path, quiet = !verbose)
    })
    invisible(tarball_path)
}

.install_from_cran <- function(x, lib, path = tempdir(), verbose, cran_mirror, current_r_version) {
    tarball_path <- file.path(path, paste(names(x), "_", x, ".tar.gz", sep = ""))
    if (!file.exists(tarball_path)) {
        .download_package(tarball_path = tarball_path, x = x, verbose = verbose)
    }
    .install_packages(tarball_path, lib, verbose, current_r_version)
    ## check and error
    if (!is.na(lib)) {
        installed_packages <- installed.packages(lib.loc = lib)
    } else {
        installed_packages <- installed.packages()
    }
    if (!names(x) %in% dimnames(installed_packages)[[1]]) {
        stop("Fail to install ", names(x), "\n")
    }
    invisible()
}

.install_from_github <- function(x,lib, verbose, current_r_version){
  pkg <- names(x)
  sha <- unname(x)
  if (utils::compareVersion(current_r_version, "3.0") != -1) {
    if (is.na(lib)) {
      if(packageVersion(devtools)>="1.6.1"){}{
        devtools::install_github(repo = pkg,ref = sha,dependencies = FALSE, upgrade = "never",force = TRUE)
      } else{
        user_repo <- strsplit(pkg,"/")[[1]]
        devtools::install_github(username = user_repo[1],repo = user_repo[2], ref = sha,dependencies = FALSE, upgrade = "never",force = TRUE)
      }
    } else {
      if(packageVersion(devtools)>="1.6.1"){}{
        devtools::install_github(repo = pkg,ref = sha,dependencies = FALSE, upgrade = "never",lib = lib,force = TRUE)
      } else{
        user_repo <- strsplit(pkg,"/")[[1]]
        devtools::install_github(username = user_repo[1],repo = user_repo[2],ref = sha,dependencies = FALSE, upgrade = "never",lib = lib,force = TRUE)
      }
    }
  } else {
    if (is.na(lib)) {
      if(packageVersion(devtools)>="1.6.1"){}{
        devtools::install_github(repo = pkg,ref = sha,dependencies = FALSE, upgrade = "never",force = TRUE)
      } else{
        user_repo <- strsplit(pkg,"/")[[1]]
        devtools::install_github(username = user_repo[1],repo = user_repo[2],ref = sha,dependencies = FALSE, upgrade = "never",force = TRUE)
      }
    } else {
      if(packageVersion(devtools)>="1.6.1"){}{
        devtools::install_github(repo = pkg,ref = sha,dependencies = FALSE, upgrade = "never",force = TRUE)
      } else{
        user_repo <- strsplit(pkg,"/")[[1]]
        devtools::install_github(username = user_repo[1],repo = user_repo[2],ref = sha,dependencies = FALSE, upgrade = "never",force = TRUE)
      }
    }
  }
  ## check and error
  if (!is.na(lib)) {
    installed_packages <- installed.packages(lib.loc = lib)
  } else {
    installed_packages <- installed.packages()
  }
  installed_gh <- strsplit(pkg,"/")[[1]][2]
  if (!installed_gh %in% dimnames(installed_packages)[[1]]) {
    stop("Fail to install ", pkg, "\n")
  }
  invisible()
}
