## generated by gran, do not edit by hand

.install_from_cran <- function(x, lib, path = tempdir(), verbose, cran_mirror) {
    url <- paste0(cran_mirror, "src/contrib/Archive/", names(x), "/", names(x), "_", x, ".tar.gz")
    tarball_path <- file.path(path, paste0(names(x), "_", x, ".tar.gz"))
    tryCatch({
        suppressWarnings(download.file(url, destfile = tarball_path, quiet = !verbose))
    }, error = function(e) {
        ## is the current latest
        url <- paste0(cran_mirror, "src/contrib/", names(x), "_", x, ".tar.gz")
        download.file(url, destfile = tarball_path, quiet = !verbose)
    })
    if (is.na(lib)) {
        install.packages(pkg = tarball_path, repos = NULL, verbose = verbose, quiet = !verbose)
    } else {
        install.packages(pkg = tarball_path, lib = lib, repos = NULL, verbose = verbose, quiet = !verbose)
    }
    ## check and error
    if (!is.na(lib)) {
        installed_packages <- installed.packages(lib.loc = lib)
    } else {
        installed_packages <- installed.packages()
    }
    if (!names(x) %in% dimnames(installed_packages)[[1]]) {
        stop("Fail to install ", names(x), "\n")
    }
    invisible()
}
